---
services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    container_name: planka
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - $PLANKA_DIRECTORY/user-avatars:/app/public/user-avatars
      - $PLANKA_DIRECTORY/project-background-images:/app/public/project-background-images
      - $PLANKA_DIRECTORY/attachments:/app/private/attachments
    ports:
      - $PLANK_HOST_PORT:1337
    environment:
      - BASE_URL=$BASE_URL
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=$SECRET_KEY
      - DEFAULT_ADMIN_EMAIL=$DEFAULT_ADMIN_EMAIL
      - DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
      - DEFAULT_ADMIN_NAME=$DEFAULT_ADMIN_NAME
      - DEFAULT_ADMIN_USERNAME=$DEFAULT_ADMIN_USERNAME
      - NODE_ENV=production
      - PUID=1000
      - PGID=1000
      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>

      # Configure knex to accept SSL certificates
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: planka-db
    restart: unless-stopped
    volumes:
      - $PLANK_DIRECTORY/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PUID=1000
      - PGID=1000

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
