---
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - $VAULTWARDEN_DIRECTORY/vw-data:/data
    ports:
      - $VAULTWARDEN_HOST_PORT:80
    restart: unless-stopped
