---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - $NEXTCLOUD_DIRECTORY/config:/config
      - $NEXTCLOUD_DIRECTORY/data:/data
    ports:
      - $NEXTCLOUD_HOST_PORT:443
    restart: unless-stopped
