---
services:
    kopia:
        image: kopia/kopia:latest
        container_name: kopia
        restart: unless-stopped
        ports:
            - $KOPIA_HOST_PORT:51515
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=admin
            - --server-password=kopiapass
        environment:
            # Set repository password
            KOPIA_PASSWORD: "$KOPIA_PASSWORD"
            #USER: "admin"
            TZ: America/Los_Angeles

        volumes:
            # Mount local folders needed by kopia
            - $KOPIA_DIRECTORY/config:/app/config
            - $KOPIA_DIRECTORY/cache:/app/cache
            - $KOPIA_DIRECTORY/logs:/app/logs
            - $MOUNT_DIRECTORY:$MOUNT_DIRECTORY:ro #mapped directory
            - $BACKUP_DIRECTORY:$BACKUP_DIRECTORY:ro
            - $KOPIA_DIRECTORY/export:/app/export
