---
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /root/my-config.yml:/app/user-data/conf.yml
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    ports:
      - '$DASHY_HOST_PORT:8080'
    volumes:
      - $DASHY_DIRECTORY/conf.yml:/app/user-data/conf.yml
      - $DASHY_DIRECTORY/sec.yml:/app/user-data/sec.yml
      - $DASHY_DIRECTORY/dashboard-icons/png:/app/user-data/item-icons/
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
